-- =====================================================================
-- TrailGo - Schema initial
-- A placer dans : src/main/resources/db/migration/V1__schema_initial.sql
--
-- Toutes les geometries sont en SRID 4326 (WGS84, le systeme du GPS).
-- ATTENTION : dans PostGIS l'ordre des coordonnees est (longitude, latitude).
-- =====================================================================

-- Active l'extension spatiale (deja faite a la main, mais on la rejoue
-- ici pour que le projet soit reinstallable sur une base vierge).
CREATE EXTENSION IF NOT EXISTS postgis;


-- =====================================================================
-- UTILISATEUR
-- =====================================================================
CREATE TABLE utilisateur (
                             id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             email           VARCHAR(180)  NOT NULL UNIQUE,
                             mot_de_passe    VARCHAR(120)  NOT NULL,
                             nom             VARCHAR(120),
                             role            VARCHAR(20)   NOT NULL DEFAULT 'TOURISTE',
                             actif           BOOLEAN       NOT NULL DEFAULT TRUE,
                             date_creation   TIMESTAMPTZ   NOT NULL DEFAULT now(),
                             CONSTRAINT chk_utilisateur_role CHECK (role IN ('ADMIN', 'TOURISTE'))
);


-- =====================================================================
-- ZONE GEOGRAPHIQUE (un polygone : ville, region, quartier)
-- =====================================================================
CREATE TABLE zone_geographique (
                                   id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nom                   VARCHAR(150)            NOT NULL,
                                   region_administrative VARCHAR(150),
                                   polygone              geometry(Polygon, 4326) NOT NULL
);

-- Index GIST : indispensable pour que les requetes spatiales soient rapides.
CREATE INDEX idx_zone_polygone ON zone_geographique USING GIST (polygone);


-- =====================================================================
-- PARCOURS
-- =====================================================================
CREATE TABLE parcours (
                          id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          titre               VARCHAR(200)  NOT NULL,
                          description         TEXT,
                          theme               VARCHAR(30)   NOT NULL,
                          duree_estimee_min   INTEGER,
                          difficulte          VARCHAR(20)   NOT NULL,
                          image_couverture    VARCHAR(500),
                          statut              VARCHAR(20)   NOT NULL DEFAULT 'BROUILLON',
                          trace               geometry(LineString, 4326),
                          bbox                geometry(Polygon, 4326),
                          distance_totale_km  NUMERIC(8,3),
                          zone_id             BIGINT        REFERENCES zone_geographique(id) ON DELETE SET NULL,
                          nb_consultations    BIGINT        NOT NULL DEFAULT 0,
                          date_creation       TIMESTAMPTZ   NOT NULL DEFAULT now(),
                          date_modification   TIMESTAMPTZ,
                          CONSTRAINT chk_parcours_theme      CHECK (theme IN ('CULTUREL','GASTRONOMIQUE','NATUREL','HISTORIQUE')),
                          CONSTRAINT chk_parcours_difficulte CHECK (difficulte IN ('FACILE','MOYEN','DIFFICILE')),
                          CONSTRAINT chk_parcours_statut     CHECK (statut IN ('BROUILLON','PUBLIE'))
);

CREATE INDEX idx_parcours_trace  ON parcours USING GIST (trace);
CREATE INDEX idx_parcours_bbox   ON parcours USING GIST (bbox);
CREATE INDEX idx_parcours_statut ON parcours (statut);
CREATE INDEX idx_parcours_theme  ON parcours (theme);


-- =====================================================================
-- ETAPE (un point du parcours, ordonne)
-- =====================================================================
CREATE TABLE etape (
                       id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       parcours_id       BIGINT                NOT NULL REFERENCES parcours(id) ON DELETE CASCADE,
                       nom               VARCHAR(200)          NOT NULL,
                       description       TEXT,
                       position          geometry(Point, 4326) NOT NULL,
                       ordre             INTEGER               NOT NULL,
                       photo             VARCHAR(500),
                       duree_visite_min  INTEGER,
    -- DEFERRABLE : permet de reordonner les etapes dans une transaction
    -- sans que la contrainte saute au milieu du reordonnancement.
                       CONSTRAINT uq_etape_ordre UNIQUE (parcours_id, ordre) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_etape_position ON etape USING GIST (position);
CREATE INDEX idx_etape_parcours ON etape (parcours_id);


-- =====================================================================
-- POINT D'INTERET (independant des parcours)
-- =====================================================================
CREATE TABLE point_interet (
                               id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               titre              VARCHAR(200)          NOT NULL,
                               categorie          VARCHAR(30)           NOT NULL,
                               adresse            VARCHAR(300),
                               position           geometry(Point, 4326) NOT NULL,
                               rayon_proximite_m  INTEGER               NOT NULL DEFAULT 200,
                               CONSTRAINT chk_poi_categorie CHECK (categorie IN
                                                                   ('RESTAURANT','MONUMENT','MUSEE','POINT_DE_VUE','HEBERGEMENT','COMMERCE','AUTRE')),
                               CONSTRAINT chk_poi_rayon CHECK (rayon_proximite_m > 0)
);

CREATE INDEX idx_poi_position ON point_interet USING GIST (position);


-- =====================================================================
-- AVIS
-- =====================================================================
CREATE TABLE avis (
                      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      parcours_id    BIGINT      NOT NULL REFERENCES parcours(id) ON DELETE CASCADE,
                      auteur_id      BIGINT      NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
                      note           SMALLINT    NOT NULL,
                      commentaire    TEXT,
                      date_creation  TIMESTAMPTZ NOT NULL DEFAULT now(),
                      signale        BOOLEAN     NOT NULL DEFAULT FALSE,
                      CONSTRAINT chk_avis_note CHECK (note BETWEEN 1 AND 5),
    -- Un utilisateur ne peut laisser qu'un seul avis par parcours.
                      CONSTRAINT uq_avis_auteur_parcours UNIQUE (parcours_id, auteur_id)
);

CREATE INDEX idx_avis_parcours ON avis (parcours_id);


-- =====================================================================
-- FAVORI (table de liaison utilisateur <-> parcours)
-- =====================================================================
CREATE TABLE favori (
                        utilisateur_id  BIGINT      NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
                        parcours_id     BIGINT      NOT NULL REFERENCES parcours(id)    ON DELETE CASCADE,
                        date_ajout      TIMESTAMPTZ NOT NULL DEFAULT now(),
                        PRIMARY KEY (utilisateur_id, parcours_id)
);

CREATE INDEX idx_favori_parcours ON favori (parcours_id);